service: products-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  environment:
    NODE_ENV: ${opt:stage, 'local'}
    PRODUCTS_TABLE: products-${opt:stage, 'local'}

plugins:
  - serverless-offline

functions:
  getAllProducts:
    handler: src/handlers/getAllProducts.handler
    events:
      - http:
          path: products
          method: get

  getProductDetails:
    handler: src/handlers/getProductDetails.handler
    events:
      - http:
          path: products/{productId}
          method: get

  addProduct:
    handler: src/handlers/addProduct.handler
    events:
      - http:
          path: products
          method: post

  processProductEvents:
    handler: src/handlers/processProductEvents.handler
    events:
      - msk:
          arn: ${env:MSK_CLUSTER_ARN}
          topic: product-event-v1-${opt:stage, 'local'}
          startingPosition: LATEST
          batchSize: 10