AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
  DomainName:
    Type: String
  SubDomain:
    Type: String
  CertificateArn:
    Type: String
    Description: Pre-created ACM certificate ARN

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'products-api-${Environment}'
      
  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      CertificateArn: !Ref CertificateArn
      
  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiDomainName
      RestApiId: !Ref ApiGateway
      Stage: !Ref Environment

Outputs:
  ApiGatewayId:
    Value: !Ref ApiGateway
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayId'