AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
  DomainName:
    Type: String
  SubDomain:
    Type: String

Resources:
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Sub '${SubDomain}.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomainName.DistributionDomainName
        HostedZoneId: !GetAtt ApiGatewayDomainName.DistributionHostedZoneId
        
  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'